# Generated by Django 6.0.1 on 2026-02-02 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterest",
            name="interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interested_users",
                to="interests.interestdomain",
            ),
        ),
        migrations.AlterField(
            model_name="userinterest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
