# Generated by Django 6.0.1 on 2026-03-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("news", "News"),
                            ("article", "Article"),
                            ("book", "Book / Research Paper"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("hi", "Hindi"),
                            ("ta", "Tamil"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("source_name", models.CharField(max_length=100)),
                ("source_url", models.URLField(unique=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_date", models.DateTimeField()),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in seconds (only for videos)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interest_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="interests.interestdomain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentItemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_tags",
                        to="content.contentitem",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_contents",
                        to="content.contenttag",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_item", "tag")},
            },
        ),
    ]
