# Generated by Django 5.2 on 2026-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="source_url",
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
