# Generated by Django 6.0.1 on 2026-02-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        ("interests", "0002_alter_userinterest_interest_alter_userinterest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="interest_domain",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_items",
                to="interests.interestdomain",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentitemtag",
            name="content_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_tags",
                to="content.contentitem",
            ),
        ),
        migrations.AlterField(
            model_name="contentitemtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_contents",
                to="content.contenttag",
            ),
        ),
    ]
