# Generated by Django 6.0.1 on 2026-03-06 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("items_per_page", models.PositiveIntegerField(default=20)),
                ("show_thumbnails", models.BooleanField(default=True)),
                (
                    "preferred_content_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("video", "Videos"),
                            ("article", "Articles"),
                            ("book", "Books"),
                            ("news", "News"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=20)),
                ("track_search_history", models.BooleanField(default=True)),
                ("track_view_history", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
