# Generated by Django 6.0.1 on 2026-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="popularity_weight",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="recency_weight",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="relevance_weight",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="language",
            field=models.CharField(default="en", max_length=20),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="preferred_content_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("video", "Videos"),
                    ("article", "Articles"),
                    ("book", "Books"),
                    ("news", "News"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_thumbnails",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="track_search_history",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="track_view_history",
            field=models.BooleanField(default=True),
        ),
    ]
